/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Irvina
 */
public class Frame2 extends javax.swing.JFrame {

    /**
     * Creates new form Frame2
     */
    public Frame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Alamat = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbKelas = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rbRPL = new javax.swing.JRadioButton();
        rbTKJ = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        Absen = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Irvina\\Pictures\\kucing imut lucu.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Alamat");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 260, 50, 30);

        Alamat.setBackground(new java.awt.Color(153, 153, 255));
        Alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlamatActionPerformed(evt);
            }
        });
        getContentPane().add(Alamat);
        Alamat.setBounds(150, 260, 140, 30);

        Nama.setBackground(new java.awt.Color(153, 153, 255));
        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        getContentPane().add(Nama);
        Nama.setBounds(150, 70, 140, 30);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 70, 40, 30);

        jLabel3.setText("BIODATA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 20, 70, 30);

        cbKelas.setBackground(new java.awt.Color(255, 204, 204));
        cbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XI RPL 1", "XI RPL 2", "XI RPL 3", "XI RPL 4", "XI RPL 5", "XI RPL 6", " " }));
        cbKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKelasActionPerformed(evt);
            }
        });
        getContentPane().add(cbKelas);
        cbKelas.setBounds(150, 180, 140, 20);

        jLabel4.setText("Absen");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 124, 50, 30);

        jLabel5.setText("Kelas");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 180, 50, 20);

        rbRPL.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(rbRPL);
        rbRPL.setText("RPL");
        getContentPane().add(rbRPL);
        rbRPL.setBounds(150, 220, 50, 23);

        rbTKJ.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(rbTKJ);
        rbTKJ.setText("TKJ");
        getContentPane().add(rbTKJ);
        rbTKJ.setBounds(200, 220, 43, 23);

        jLabel6.setText("Jurusan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 220, 50, 20);

        Absen.setBackground(new java.awt.Color(153, 153, 255));
        Absen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbsenActionPerformed(evt);
            }
        });
        getContentPane().add(Absen);
        Absen.setBounds(150, 120, 140, 30);

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 0));
        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 313, 70, 30);

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 0));
        jButton2.setText("Exit");
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 313, 70, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Irvina\\Documents\\gambar blog.jpg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(300, 60, 180, 270);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 480, 360);

        setBounds(0, 0, 498, 403);
    }// </editor-fold>//GEN-END:initComponents

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void AlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlamatActionPerformed

    private void AbsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbsenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AbsenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String nama = Nama.getText();
    String absen = Absen.getText();
    String kelas = cbKelas.getSelectedItem().toString();
    String alamat = Alamat.getText();
    String jurusan;
    
    if (rbRPL.isSelected())
        jurusan = "RPL";
    else if (rbTKJ.isSelected())
        jurusan = "TKJ";
    else
        jurusan = " ";

    if (cbKelas.getSelectedItem()== "XIRPL1"){
    }//GEN-LAST:event_jButton1ActionPerformed

    if(cbKelas.getSelectedItem()== "XI RPL 2"){
           
    } if(cbKelas.getSelectedItem()== "XI RPL 3"){
           
    } if(cbKelas.getSelectedItem()== "XI RPL 4"){
           
    } if(cbKelas.getSelectedItem()== "XI RPL 5"){
           
    } if(cbKelas.getSelectedItem()== "XI RPL 6");
    
    }
    
    private void cbKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKelasActionPerformed
   
       
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absen;
    private javax.swing.JTextField Alamat;
    private javax.swing.JTextField Nama;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbKelas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbRPL;
    private javax.swing.JRadioButton rbTKJ;
    // End of variables declaration//GEN-END:variables
}
