
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Irvina
 */
public class Frame5 extends javax.swing.JFrame {
          String temp = "";
        Double tinggi, berat, id;
    /**
     * Creates new form Frame5
     */
    public Frame5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        btnCobaLagi = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        Nama = new javax.swing.JTextField();
        Tinggi = new javax.swing.JTextField();
        BB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        Ideal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Diagnosa1 = new javax.swing.JTextField();
        Diagnosa2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rb2 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 70, 40, 20);

        jLabel3.setText("Tinggi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 130, 60, 20);

        jLabel4.setText("Berat Badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 180, 90, 20);

        jLabel5.setText("Berat badan Ideal anda adalah");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 330, 200, 30);

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        getContentPane().add(btnHitung);
        btnHitung.setBounds(90, 270, 80, 30);

        btnCobaLagi.setText("Coba Lagi");
        btnCobaLagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobaLagiActionPerformed(evt);
            }
        });
        getContentPane().add(btnCobaLagi);
        btnCobaLagi.setBounds(190, 270, 100, 30);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar);
        btnKeluar.setBounds(310, 270, 80, 30);

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        getContentPane().add(Nama);
        Nama.setBounds(150, 60, 190, 30);

        Tinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TinggiActionPerformed(evt);
            }
        });
        getContentPane().add(Tinggi);
        Tinggi.setBounds(150, 120, 80, 30);
        getContentPane().add(BB);
        BB.setBounds(150, 170, 80, 30);

        jLabel6.setText("Jenis Kelamin");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 230, 90, 20);

        buttonGroup1.add(rb1);
        rb1.setText("Perempuan");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        getContentPane().add(rb1);
        rb1.setBounds(140, 220, 130, 40);

        Ideal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdealActionPerformed(evt);
            }
        });
        getContentPane().add(Ideal);
        Ideal.setBounds(290, 330, 80, 30);

        jLabel7.setText("kg");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(240, 170, 40, 20);

        jLabel8.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 380, 150, 30);

        Diagnosa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Diagnosa1ActionPerformed(evt);
            }
        });
        getContentPane().add(Diagnosa1);
        Diagnosa1.setBounds(100, 420, 340, 30);

        Diagnosa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Diagnosa2ActionPerformed(evt);
            }
        });
        getContentPane().add(Diagnosa2);
        Diagnosa2.setBounds(100, 470, 340, 30);

        jLabel9.setText("cm");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(380, 340, 40, 20);

        jLabel10.setText("cm");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(240, 120, 40, 20);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("CEK IDEAL TUBUH");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(150, 10, 150, 40);

        buttonGroup1.add(rb2);
        rb2.setText("Laki-laki");
        jPanel2.add(rb2);
        rb2.setBounds(290, 220, 130, 40);

        jLabel11.setText("Hasil");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(30, 420, 60, 30);

        jLabel12.setText("Saran");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(30, 474, 50, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 450, 510);

        setBounds(0, 0, 470, 549);
    }// </editor-fold>//GEN-END:initComponents

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void TinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TinggiActionPerformed

    private void IdealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdealActionPerformed

    private void Diagnosa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Diagnosa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Diagnosa1ActionPerformed

    private void Diagnosa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Diagnosa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Diagnosa2ActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        if (Nama.getText().equals("")||BB.getText().equals("")
        ||Tinggi.getText().equals("")) {
          JOptionPane.showMessageDialog(null, "Kotak harus diisi semua");
      } else if(rb1.isSelected()||rb2.isSelected()) {
          try {
              Proses();
          }catch (Exception e) {
              JOptionPane.showMessageDialog(null, "Inputan ada yang salah");
          }
      }else {
          JOptionPane.showMessageDialog(null, "Pilih jenis kelamin");
      }// TODO add your handling code here:
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnCobaLagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobaLagiActionPerformed
        Nama.setText("");
        Tinggi.setText("");
        BB.setText("");
        Diagnosa1.setText("");
        Diagnosa2.setText("");
        Ideal.setText("");
        buttonGroup1.clearSelection();// TODO add your handling code here:
    }//GEN-LAST:event_btnCobaLagiActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
    rb2.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_rb1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BB;
    private javax.swing.JTextField Diagnosa1;
    private javax.swing.JTextField Diagnosa2;
    private javax.swing.JTextField Ideal;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JButton btnCobaLagi;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    // End of variables declaration//GEN-END:variables

private void Proses() {
       tinggi = Double.parseDouble(Tinggi.getText());
       berat = Double.parseDouble(BB.getText());
       
       if (rb2.isSelected()) {
           id = (tinggi - 100) * 1;
       } else if (rb1.isSelected()) {
           id = (tinggi - 104) * 1;
       }
       temp = Double.toString(id.intValue());
       
       if (id < berat) {
           Ideal.setText(temp);
           Diagnosa1.setText("Sorry " + "\n" + Nama.getText() +"\n"+ " Sepertinya Anda Overweight");
           Diagnosa2.setText("Banyak olahraga dan hindari makanan kolesterol tinggi");
       } else if (id > berat) {
           Ideal.setText(temp);
           Diagnosa1.setText("Sorry " + "\n" + Nama.getText() + "\n" + " Sepertinya Anda Underweight");
           Diagnosa2.setText("Banyak konsumsi makanan berprotein tinggi");
       } else {
           Ideal.setText(temp);
           Diagnosa1.setText("Congratulatioon !! " + "\n" + Nama.getText()  + "\n" + " Berat Badan Anda Ideal");
           Diagnosa2.setText("Lanjutkan Pola Hidup Sehatmu ^^9");
       }
    }
}
