/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Helga
 */
public class Modul7_1_Frame2 extends javax.swing.JFrame {

    /**
     * Creates new form Modul7_1_Frame2
     */
    public Modul7_1_Frame2(String Nama, String Absen, String Kelas, String Jurusan, String Alamat) {
        initComponents();
        
        Hasil1.setText(Nama);
        Hasil2.setText(Absen);
        Hasil3.setText(Kelas);
        Hasil4.setText(Jurusan);
        Hasil5.setText(Alamat);
    }

    private Modul7_1_Frame2() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hasil1 = new javax.swing.JLabel();
        Hasil5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Hasil2 = new javax.swing.JLabel();
        Hasil3 = new javax.swing.JLabel();
        Hasil4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Hasil1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Hasil1.setText("Hasil 1");
        getContentPane().add(Hasil1);
        Hasil1.setBounds(80, 80, 50, 13);

        Hasil5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Hasil5.setText("Hasil 5");
        getContentPane().add(Hasil5);
        Hasil5.setBounds(80, 240, 50, 13);

        jLabel3.setFont(new java.awt.Font("Hobo Std", 1, 14)); // NOI18N
        jLabel3.setText("Hasil Biodata");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 40, 120, 15);

        Hasil2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Hasil2.setText("Hasil 2");
        getContentPane().add(Hasil2);
        Hasil2.setBounds(80, 120, 50, 13);

        Hasil3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Hasil3.setText("Hasil 3");
        getContentPane().add(Hasil3);
        Hasil3.setBounds(80, 160, 50, 13);

        Hasil4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Hasil4.setText("Hasil 4");
        getContentPane().add(Hasil4);
        Hasil4.setBounds(80, 200, 50, 13);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modul7_1_Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modul7_1_Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modul7_1_Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modul7_1_Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modul7_1_Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hasil1;
    private javax.swing.JLabel Hasil2;
    private javax.swing.JLabel Hasil3;
    private javax.swing.JLabel Hasil4;
    private javax.swing.JLabel Hasil5;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
